[package]
name = "vegafusion-convert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_runtime = "0.79.0"
tokio = {version="1.21.2", features=["macros"]}
serde_json = "1.0.85"

[build-dependencies]
serde_json = "1.0.85"