[workspace]
edition = "2021"
resolver = "2"  # Needed for proper wgpu compilation

members = [
    "vegafusion-convert",
    "vl2vg"
]

[profile.release]
#strip = true  # Automatically strip symbols from the binary
opt-level = "z"  # Optimize for size
lto = true
codegen-units = 1