[package]
name = "vl-convert-python"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "vl_convert"
crate-type = ["cdylib"]

[dependencies]
vl-convert-rs = { path = "../vl-convert-rs" }
pyo3 = { version = "0.17.1", features = ["extension-module", "anyhow"] }
lazy_static = "1.4.0"
futures = "0.3.24"
