[package]
name = "vl-convert-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_core = "0.153.0"
serde_json = "1.0.85"

[dev-dependencies]
tokio = {version="1.21.2", features=["macros", "rt"]}

[build-dependencies]
serde_json = "1.0.85"