[package]
name = "vl-convert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vl-convert-rs = {path= "../vl-convert-rs" }
tokio = {version="1.21.2", features=["macros", "rt-multi-thread"]}
serde_json = "1.0.85"
clap = {version="4.0.6", features=["derive"]}
