[package]
name = "vegafusion-convert"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_runtime = "0.79.0"
serde_json = "1.0.85"

[dev-dependencies]
tokio = {version="1.21.2", features=["macros"]}

[build-dependencies]
serde_json = "1.0.85"